version: "3.8" # can be omitted for newest compose

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_node
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: backend_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
